<?php

/**
 * Field definitions for the lablab builder slideshow module.
 *
 * @link       https://github.com/team-ok
 * @since      1.0.0
 * @author     Timo Klemm
 */

if( ! defined( 'ABSPATH' ) ) exit;

return array (
	array (
		'key' => 'field_57fdfe9c24de6',
		'label' => __('Slides', 'lablab-slideshow'),
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'top',
		'endpoint' => 0,
	),
	array (
		'key' => 'field_57fb84f5aa281',
		'label' => __('Create Slides', 'lablab-slideshow'),
		'name' => 'lablab_slides',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => 'lablab-slides',
			'id' => '',
		),
		'collapsed' => 'field_58049f8e0e8c5',
		'min' => 0,
		'max' => 0,
		'layout' => 'block',
		'button_label' => __('Add Slide', 'lablab-slideshow'),
		'sub_fields' => array (
			array (
				'key' => 'field_58049f8e0e8c5',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array (
				'key' => 'field_57fc9f1a1027e',
				'label' => __('Content Source', 'lablab-slideshow'),
				'name' => 'lablab_slide_content_source',
				'type' => 'radio',
				'instructions' => __('When \'From a post\' is selected, the title, the post image and the excerpt of a selected post (if available) are fetched automatically.', 'lablab-slideshow'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => 'lablab-slide-content-source',
					'id' => '',
				),
				'choices' => array (
					'manually' => __('Manually', 'lablab-slideshow'),
					'from_post' => __('From a post', 'lablab-slideshow'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57fc9e2c1027d',
				'label' => __('Select Post', 'lablab-slideshow'),
				'name' => 'lablab_slide_post_object',
				'type' => 'post_object',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fc9f1a1027e',
							'operator' => '==',
							'value' => 'from_post',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => 'lablab-slide-post-object',
					'id' => '',
				),
				'post_type' => array (
					0 => 'page',
					1 => 'post',
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'multiple' => 0,
				'return_format' => 'object',
				'ui' => 1,
			),
			array (
				'key' => 'field_57fdf916834b4',
				'label' => __('Slide-Type', 'lablab-slideshow'),
				'name' => 'lablab_slide_type',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fc9f1a1027e',
							'operator' => '==',
							'value' => 'manually',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => 'lablab-slide-type',
					'id' => '',
				),
				'choices' => array (
					'background_color' => __('Background Color', 'lablab-slideshow'),
					'image' => __('Image', 'lablab-slideshow'),
					'video' => __('Video', 'lablab-slideshow'),
					'iframe' => __('Iframe', 'lablab-slideshow'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57fb85afaa282',
				'label' => __('Image', 'lablab-slideshow'),
				'name' => 'lablab_slide_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fdf916834b4',
							'operator' => '==',
							'value' => 'image',
						),
					),
					array (
						array (
							'field' => 'field_57fc9f1a1027e',
							'operator' => '==',
							'value' => 'from_post',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => 'lablab-slide-image',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array (
				'key' => 'field_57fdf6d4a9aab',
				'label' => __('Video', 'lablab-slideshow'),
				'name' => 'lablab_slide_video',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fc9f1a1027e',
							'operator' => '==',
							'value' => 'manually',
						),
						array (
							'field' => 'field_57fdf916834b4',
							'operator' => '==',
							'value' => 'video',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => 'mp4, webm, ogv',
			),
			array (
				'key' => 'field_57fdfc69017ed',
				'label' => __('Iframe', 'lablab-slideshow'),
				'name' => 'lablab_slide_iframe',
				'type' => 'textarea',
				'instructions' => __('Insert Iframe-Code (e.g. from YouTube) here', 'lablab-slideshow'),
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fc9f1a1027e',
							'operator' => '==',
							'value' => 'manually',
						),
						array (
							'field' => 'field_57fdf916834b4',
							'operator' => '==',
							'value' => 'iframe',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => '',
			),
			array (
				'key' => 'field_57fdfd39017ef',
				'label' => __('Choose Color', 'lablab-slideshow'),
				'name' => 'lablab_slide_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fc9f1a1027e',
							'operator' => '==',
							'value' => 'manually',
						),
						array (
							'field' => 'field_57fdf916834b4',
							'operator' => '==',
							'value' => 'background_color',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#CCCCCC',
			),
			array (
				'key' => 'field_57fb866aaa284',
				'label' => __('Overlay-Title', 'lablab-slideshow'),
				'name' => 'lablab_slide_overlay_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => 'lablab-slide-overlay-title',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57fb85f0aa283',
				'label' => __('Overlay-Text', 'lablab-slideshow'),
				'name' => 'lablab_slide_overlay_text',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => 'lablab-slide-overlay-text',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => 200,
				'rows' => 3,
				'new_lines' => 'br',
			),
			array (
				'key' => 'field_57fb929f06e55',
				'label' => __('Overlay-Text-Position', 'lablab-slideshow'),
				'name' => 'lablab_slide_overlay_position',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					'center' => __('Center', 'lablab-slideshow'),
					'top' => __('Top', 'lablab-slideshow'),
					'right' => __('Right', 'lablab-slideshow'),
					'bottom' => __('Bottom', 'lablab-slideshow'),
					'left' => __('Left', 'lablab-slideshow'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57fdf19215572',
				'label' => __('Overlay-Text-Background', 'lablab-slideshow'),
				'name' => 'lablab_slide_overlay_background',
				'type' => 'true_false',
				'instructions' => __('Show text on a contrasting background?', 'lablab-slideshow'),
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 0,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array (
				'key' => 'field_57fc9a1f075f0',
				'label' => __('Link', 'lablab-slideshow'),
				'name' => 'lablab_slide_link',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fc9f1a1027e',
							'operator' => '==',
							'value' => 'manually',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array (
					0 => __('No link', 'lablab-slideshow'),
					'internal' => __('Internal', 'lablab-slideshow'),
					'external' => __('External', 'lablab-slideshow'),
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
			),
			array (
				'key' => 'field_57fc982e075ee',
				'label' => __('Internal Link', 'lablab-slideshow'),
				'name' => 'lablab_slide_link_internal',
				'type' => 'page_link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fc9a1f075f0',
							'operator' => '==',
							'value' => 'internal',
						),
						array (
							'field' => 'field_57fc9f1a1027e',
							'operator' => '==',
							'value' => 'manually',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array (
					0 => 'page',
					1 => 'post',
				),
				'taxonomy' => array (
				),
				'allow_null' => 0,
				'allow_archives' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_57fc99e2075ef',
				'label' => __('External Link', 'lablab-slideshow'),
				'name' => 'lablab_slide_link_external',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array (
					array (
						array (
							'field' => 'field_57fc9a1f075f0',
							'operator' => '==',
							'value' => 'external',
						),
						array (
							'field' => 'field_57fc9f1a1027e',
							'operator' => '==',
							'value' => 'manually',
						),
					),
				),
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
		),
	),
	array (
		'key' => 'field_57fdfdd91f8fe',
		'label' => __('Settings', 'lablab-slideshow'),
		'name' => '',
		'type' => 'tab',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'placement' => 'top',
		'endpoint' => 0,
	),
	array (
		'key' => 'field_5831718bffc41',
		'label' => __('Slideshow-Width', 'lablab-slideshow'),
		'name' => 'lablab_slider_width',
		'type' => 'radio',
		'instructions' => __('Full width or value in pixels', 'lablab-slideshow'),
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array (
			'full' => __('Full Width', 'lablab-slideshow'),
		),
		'allow_null' => 0,
		'other_choice' => 1,
		'save_other_choice' => 0,
		'default_value' => 'full',
		'layout' => 'horizontal',
		'return_format' => 'value',
	),
	array (
		'key' => 'field_59316edccbdf7',
		'label' => __('Center Slideshow?', 'lablab-slideshow'),
		'name' => 'lablab_slider_center',
		'type' => 'radio',
		'instructions' => __('Should the slideshow be centered horizontally?', 'lablab-slideshow'),
		'required' => 0,
		'conditional_logic' => array (
			array (
				array (
					'field' => 'field_5831718bffc41',
					'operator' => '!=',
					'value' => 'full',
				),
			),
		),
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array (
			1 => __('Yes', 'lablab-slideshow'),
			0 => __('No', 'lablab-slideshow'),
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'save_other_choice' => 0,
		'default_value' => 1,
		'layout' => 'horizontal',
		'return_format' => 'value',
	),
	array (
		'key' => 'field_57fe277c8372e',
		'label' => __('Slideshow-Height', 'lablab-slideshow'),
		'name' => 'lablab_slider_height',
		'type' => 'number',
		'instructions' => __('Value in pixels', 'lablab-slideshow'),
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => 400,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => 100,
		'max' => '',
		'step' => '',
	),
	array (
		'key' => 'field_57fe0fabfcd60',
		'label' => __('Autoplay', 'lablab-slideshow'),
		'name' => 'lablab_slider_autoplay',
		'type' => 'true_false',
		'instructions' => __('Autoplay slideshow?', 'lablab-slideshow'),
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 0,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array (
		'key' => 'field_57fe122ab9322',
		'label' => __('Autoslide-Interval', 'lablab-slideshow'),
		'name' => 'lablab_slider_autoplay_interval',
		'type' => 'number',
		'instructions' => __('Length of the interval between two slides (in seconds)', 'lablab-slideshow'),
		'required' => 0,
		'conditional_logic' => array (
			array (
				array (
					'field' => 'field_57fe0fabfcd60',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => 7,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => 1,
		'max' => '',
		'step' => 1,
	),
	array (
		'key' => 'field_57fdf2a015573',
		'label' => __('Animation-Type', 'lablab-slideshow'),
		'name' => 'lablab_slider_animation',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array (
			'fade' => __('Fade', 'lablab-slideshow'),
			'scroll' => __('Scroll', 'lablab-slideshow'),
			'scale' => __('Scale', 'lablab-slideshow'),
			'swipe' => __('Swipe', 'lablab-slideshow'),
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'save_other_choice' => 0,
		'default_value' => 'swipe',
		'layout' => 'horizontal',
		'return_format' => 'value',
	),
	array (
		'key' => 'field_57ff595c7a3e0',
		'label' => __('Animation-Duration', 'lablab-slideshow'),
		'name' => 'lablab_slider_animation_duration',
		'type' => 'number',
		'instructions' => __('Value in milliseconds', 'lablab-slideshow'),
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => 500,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => 50,
		'max' => '',
		'step' => 50,
	),
	array (
		'key' => 'field_57fdf56115574',
		'label' => __('Ken Burns-Effect', 'lablab-slideshow'),
		'name' => 'lablab_slider_kenburns',
		'type' => 'true_false',
		'instructions' => __('Activate Ken Burns-Effect (Pan & Zoom)?', 'lablab-slideshow'),
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'message' => '',
		'default_value' => 0,
		'ui' => 0,
		'ui_on_text' => '',
		'ui_off_text' => '',
	),
	array (
		'key' => 'field_57ff5a1b7a3e1',
		'label' => __('Ken Burns-Effect Duration', 'lablab-slideshow'),
		'name' => 'lablab_slider_kenburns_duration',
		'type' => 'number',
		'instructions' => __('Value in seconds', 'lablab-slideshow'),
		'required' => 0,
		'conditional_logic' => array (
			array (
				array (
					'field' => 'field_57fdf56115574',
					'operator' => '==',
					'value' => '1',
				),
			),
		),
		'wrapper' => array (
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => 15,
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'min' => 1,
		'max' => '',
		'step' => 1,
	),
);